server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/skillrat_user?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: false
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

  redis:
    host: localhost
    port: 6379

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/oauth2/jwks

  mail:
    host: smtp.gmail.com
    port: 587
    username: hltsolutions.info@gmail.com
    password: chym buqc toiw wtzw
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

skillrat:
  gateway:
    check-token-cache-ttl-seconds: 30
  coins:
    education:
      perAction: 10
      maxPerCategory: 30
    project:
      perAction: 10
      maxPerCategory: 50
    internship:
      perAction: 10
      maxPerCategory: 50
    skill:
      perAction: 2
      maxPerCategory: 40
    title:
      perAction: 5
      maxPerCategory: 25

management:
  endpoints:
    web:
      exposure:
        include: "*"
