server:
  port: 8085
spring:
  application:
    name: gateway-service
  redis:
    host: redis
    port: 6379
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**
        - id: org
          uri: http://organisation-service:8082
          predicates:
            - Path=/api/organisations/**
        - id: placement
          uri: http://placement-service:8083
          predicates:
            - Path=/api/placements/**
        - id: wallet
          uri: http://wallet-service:8084
          predicates:
            - Path=/api/wallet/**
      default-filters:
        - RemoveRequestHeader=Cookie
skillrat:
  gateway:
    check-token-cache-ttl-seconds: 30
management:
  endpoints:
    web:
      exposure:
        include: "*"
