server:
  port: 9443
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
        - id: user-roles
          uri: http://localhost:8081
          predicates:
            - Path=/api/roles/**
        - id: org
          uri: http://localhost:8082
          predicates:
            - Path=/api/organisations/**
        - id: placement
          uri: http://localhost:8083
          predicates:
            - Path=/api/placements/**
        - id: wallet
          uri: http://localhost:8084
          predicates:
            - Path=/api/wallet/**
      default-filters:
        - RemoveRequestHeader=Cookie
skillrat:
  gateway:
    check-token-cache-ttl-seconds: 30
management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
